export const liquidationRunAbi = [
    {
      name: "checkIn",
      type: "function",
      stateMutability: "payable",
      inputs: [],
      outputs: [],
    },
    {
      name: "submitScore",
      type: "function",
      stateMutability: "payable",
      inputs: [
        { name: "_timeMs", type: "uint32" },
        { name: "_v", type: "uint8" },
        { name: "_r", type: "bytes32" },
        { name: "_s", type: "bytes32" },
      ],
      outputs: [],
    },
    {
      name: "checkInStreakDays",
      type: "function",
      stateMutability: "view",
      inputs: [{ name: "", type: "address" }],
      outputs: [{ name: "", type: "uint32" }],
    },
    {
      name: "bestTimeMs",
      type: "function",
      stateMutability: "view",
      inputs: [{ name: "", type: "address" }],
      outputs: [{ name: "", type: "uint32" }],
    },
    {
      name: "canCheckIn",
      type: "function",
      stateMutability: "view",
      inputs: [{ name: "_player", type: "address" }],
      outputs: [{ name: "", type: "bool" }],
    },
    {
      name: "getCurrentStreak",
      type: "function",
      stateMutability: "view",
      inputs: [{ name: "_player", type: "address" }],
      outputs: [{ name: "", type: "uint32" }],
    },
    {
      name: "checkInPrice",
      type: "function",
      stateMutability: "view",
      inputs: [],
      outputs: [{ name: "", type: "uint256" }],
    },
    {
      name: "submitScorePrice",
      type: "function",
      stateMutability: "view",
      inputs: [],
      outputs: [{ name: "", type: "uint256" }],
    },
    {
      name: "nonces",
      type: "function",
      stateMutability: "view",
      inputs: [{ name: "", type: "address" }],
      outputs: [{ name: "", type: "uint256" }],
    },
  ] as const;